using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace TavernTrashers.Api.Common.SourceGenerators;

[Generator]
public class ModuleBoilerplateGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor NotPartialDescriptor = new(
        id: "TT0001",
        title: "Module class must be partial",
        messageFormat: "Class '{0}' is decorated with [GenerateModuleBoilerplate] but is not declared partial. Add the 'partial' modifier to allow the source generator to emit the required property overrides.",
        category: "ModuleBoilerplateGenerator",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) => node is ClassDeclarationSyntax,
                transform: (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
            .Where(classDecl => classDecl.AttributeLists.Count > 0);

        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndClasses, (spc, source) =>
        {
            var (compilation, classDecls) = source;
            foreach (var classDecl in classDecls)
            {
                var semanticModel = compilation.GetSemanticModel(classDecl.SyntaxTree);
                var symbol = semanticModel.GetDeclaredSymbol(classDecl);
                if (symbol is null)
                    continue;

                var attributeData = symbol.GetAttributes().FirstOrDefault(attr =>
                    attr.AttributeClass?.Name == nameof(GenerateModuleBoilerplateAttribute) ||
                    attr.AttributeClass?.ToDisplayString() == typeof(GenerateModuleBoilerplateAttribute).FullName);
                if (attributeData is null)
                    continue;

                var ns = symbol.ContainingNamespace.ToDisplayString();
                var className = symbol.Name;
                var moduleName = attributeData.ConstructorArguments[0].Value?.ToString() ?? className.Replace("Module", "");
                var moduleSchema = attributeData.ConstructorArguments[1].Value?.ToString() ?? "default_schema";

                var isPartial = classDecl.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword));
                if (!isPartial)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(NotPartialDescriptor, classDecl.GetLocation(), className));
                }

                GenerateBoilerplate(spc, ns, className, moduleName, moduleSchema, isPartial);
            }
        });
    }

    private static void GenerateBoilerplate(SourceProductionContext context, string ns, string className, string moduleName, string moduleSchema, bool isPartial)
    {
        // Add IdempotentDomainEventHandler generation
        var moduleSpecificIdempotentDomainEventHandlerSource = new StringBuilder();
        moduleSpecificIdempotentDomainEventHandlerSource.AppendLine("// <auto-generated/>");
        moduleSpecificIdempotentDomainEventHandlerSource.AppendLine("// This file was generated by ModuleBoilerplateGenerator.");
        moduleSpecificIdempotentDomainEventHandlerSource.AppendLine("using TavernTrashers.Api.Common.Application.Data;");
        moduleSpecificIdempotentDomainEventHandlerSource.AppendLine("using TavernTrashers.Api.Common.Application.Messaging;");
        moduleSpecificIdempotentDomainEventHandlerSource.AppendLine("using TavernTrashers.Api.Common.Domain.Entities;");
        moduleSpecificIdempotentDomainEventHandlerSource.AppendLine("using TavernTrashers.Api.Common.Infrastructure.Outbox;");
        moduleSpecificIdempotentDomainEventHandlerSource.AppendLine($"namespace {ns}");
        moduleSpecificIdempotentDomainEventHandlerSource.AppendLine("{");
        moduleSpecificIdempotentDomainEventHandlerSource.AppendLine(
            $"    public class {moduleName}IdempotentDomainEventHandler<TDomainEvent>(IDomainEventHandler<TDomainEvent> decorated, IDbConnectionFactory dbConnectionFactory) : IdempotentDomainEventHandlerBase<TDomainEvent>(decorated, dbConnectionFactory) where TDomainEvent : IDomainEvent");
        moduleSpecificIdempotentDomainEventHandlerSource.AppendLine("    {");
        moduleSpecificIdempotentDomainEventHandlerSource.AppendLine($"        protected override string Schema => \"{moduleSchema}\";");
        moduleSpecificIdempotentDomainEventHandlerSource.AppendLine("    }");
        moduleSpecificIdempotentDomainEventHandlerSource.AppendLine("}");
        context.AddSource($"{moduleName}IdempotentDomainEventHandler.g.cs", SourceText.From(moduleSpecificIdempotentDomainEventHandlerSource.ToString(), Encoding.UTF8));
        
        // Add IdempotentIntegrationEventHandler generation
        var moduleSpecificIdempotentIntegrationEventHandlerSource = new StringBuilder();
        moduleSpecificIdempotentIntegrationEventHandlerSource.AppendLine("// <auto-generated/>");
        moduleSpecificIdempotentIntegrationEventHandlerSource.AppendLine("// This file was generated by ModuleBoilerplateGenerator.");
        moduleSpecificIdempotentIntegrationEventHandlerSource.AppendLine("using TavernTrashers.Api.Common.Application.Data;");
        moduleSpecificIdempotentIntegrationEventHandlerSource.AppendLine("using TavernTrashers.Api.Common.Application.EventBus;");
        moduleSpecificIdempotentIntegrationEventHandlerSource.AppendLine("using TavernTrashers.Api.Common.Infrastructure.Inbox;");
        moduleSpecificIdempotentIntegrationEventHandlerSource.AppendLine($"namespace {ns}");
        moduleSpecificIdempotentIntegrationEventHandlerSource.AppendLine("{");
        moduleSpecificIdempotentIntegrationEventHandlerSource.AppendLine($"    public class {moduleName}IdempotentIntegrationEventHandler<TIntegrationEvent>(IIntegrationEventHandler<TIntegrationEvent> decorated, IDbConnectionFactory dbConnectionFactory) : IdempotentIntegrationEventHandlerBase<TIntegrationEvent>(decorated, dbConnectionFactory) where TIntegrationEvent : IntegrationEvent");
        moduleSpecificIdempotentIntegrationEventHandlerSource.AppendLine("    {");
        moduleSpecificIdempotentIntegrationEventHandlerSource.AppendLine($"        protected override string Schema => \"{moduleSchema}\";");
        moduleSpecificIdempotentIntegrationEventHandlerSource.AppendLine("    }");
        moduleSpecificIdempotentIntegrationEventHandlerSource.AppendLine("}");
        context.AddSource($"{moduleName}IdempotentIntegrationEventHandler.g.cs", SourceText.From(moduleSpecificIdempotentIntegrationEventHandlerSource.ToString(), Encoding.UTF8));

        // Add IntegrationEventConsumer generation
        var moduleSpecificIntegrationEventConsumerSource = new StringBuilder();
        moduleSpecificIntegrationEventConsumerSource.AppendLine("// <auto-generated/>");
        moduleSpecificIntegrationEventConsumerSource.AppendLine("// This file was generated by ModuleBoilerplateGenerator.");
        moduleSpecificIntegrationEventConsumerSource.AppendLine("using TavernTrashers.Api.Common.Application.Data;");
        moduleSpecificIntegrationEventConsumerSource.AppendLine("using TavernTrashers.Api.Common.Application.EventBus;");
        moduleSpecificIntegrationEventConsumerSource.AppendLine("using TavernTrashers.Api.Common.Infrastructure.Inbox;");
        moduleSpecificIntegrationEventConsumerSource.AppendLine($"namespace {ns}");
        moduleSpecificIntegrationEventConsumerSource.AppendLine("{");
        moduleSpecificIntegrationEventConsumerSource.AppendLine($"    public class {moduleName}IntegrationEventConsumer<TIntegrationEvent>(IDbConnectionFactory dbConnectionFactory) : IntegrationEventConsumerBase<TIntegrationEvent>(dbConnectionFactory) where TIntegrationEvent : IntegrationEvent");
        moduleSpecificIntegrationEventConsumerSource.AppendLine("    {");
        moduleSpecificIntegrationEventConsumerSource.AppendLine($"        protected override string Schema => \"{moduleSchema}\";");
        moduleSpecificIntegrationEventConsumerSource.AppendLine("    }");
        moduleSpecificIntegrationEventConsumerSource.AppendLine("}");
        context.AddSource($"{moduleName}IntegrationEventConsumer.g.cs", SourceText.From(moduleSpecificIntegrationEventConsumerSource.ToString(), Encoding.UTF8));

        // Generate partial class overrides for compile-time type references
        if (!isPartial)
            return;

        var modulePartialClassSource = new StringBuilder();
        modulePartialClassSource.AppendLine("// <auto-generated/>");
        modulePartialClassSource.AppendLine("// This file was generated by ModuleBoilerplateGenerator.");
        modulePartialClassSource.AppendLine("using System;");
        modulePartialClassSource.AppendLine($"namespace {ns}");
        modulePartialClassSource.AppendLine("{");
        modulePartialClassSource.AppendLine($"    public partial class {className}");
        modulePartialClassSource.AppendLine("    {");
        modulePartialClassSource.AppendLine($"        public override Type IntegrationEventConsumerType => typeof({moduleName}IntegrationEventConsumer<>);");
        modulePartialClassSource.AppendLine($"        public override Type IdempotentDomainEventHandlerType => typeof({moduleName}IdempotentDomainEventHandler<>);");
        modulePartialClassSource.AppendLine($"        public override Type IdempotentIntegrationEventHandlerType => typeof({moduleName}IdempotentIntegrationEventHandler<>);");
        modulePartialClassSource.AppendLine("    }");
        modulePartialClassSource.AppendLine("}");
        context.AddSource($"{className}.g.cs", SourceText.From(modulePartialClassSource.ToString(), Encoding.UTF8));
    }
}