// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TavernTrashers.Api.Modules.Characters.Infrastructure.Database;

#nullable disable

namespace TavernTrashers.Api.Modules.Characters.Infrastructure.Database.Migrations
{
    [DbContext(typeof(CharactersDbContext))]
    [Migration("20260330000002_AddCampaignSupport")]
    partial class AddCampaignSupport
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
