// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TavernTrashers.Api.Modules.Characters.Infrastructure.Database;

#nullable disable

namespace TavernTrashers.Api.Modules.Characters.Infrastructure.Database.Migrations
{
    [DbContext(typeof(CharactersDbContext))]
    partial class CharactersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("characters")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TavernTrashers.Api.Common.Infrastructure.Auditing.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("text")
                        .HasColumnName("affected_columns");

                    b.Property<string>("NewValues")
                        .HasMaxLength(3000)
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("OldValues")
                        .HasMaxLength(3000)
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("jsonb")
                        .HasColumnName("primary_key");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("table_name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.ToTable("audit_logs", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Characters.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.ToTable("characters", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.ClassLevels.ClassLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_class_id");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.HasKey("Id")
                        .HasName("pk_class_levels");

                    b.HasIndex("CharacterClassId")
                        .HasDatabaseName("ix_class_levels_character_class_id");

                    b.HasIndex("CharacterId", "CharacterClassId")
                        .IsUnique()
                        .HasDatabaseName("ix_class_levels_character_id_character_class_id");

                    b.ToTable("class_levels", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Classes.CharacterClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsHomebrew")
                        .HasColumnType("boolean")
                        .HasColumnName("is_homebrew");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_character_classes");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_character_classes_name");

                    b.ToTable("character_classes", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Resources.CharacterResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<int>("CurrentAmount")
                        .HasColumnType("integer")
                        .HasColumnName("current_amount");

                    b.Property<int>("MaxAmount")
                        .HasColumnType("integer")
                        .HasColumnName("max_amount");

                    b.Property<Guid>("ResourceDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_definition_id");

                    b.HasKey("Id")
                        .HasName("pk_character_resources");

                    b.HasIndex("ResourceDefinitionId")
                        .HasDatabaseName("ix_character_resources_resource_definition_id");

                    b.HasIndex("CharacterId", "ResourceDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("ix_character_resources_character_id_resource_definition_id");

                    b.ToTable("character_resources", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Resources.ResourceDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_class_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_resource_definitions");

                    b.HasIndex("CharacterClassId")
                        .HasDatabaseName("ix_resource_definitions_character_class_id");

                    b.ToTable("resource_definitions", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.ClassLevels.ClassLevel", b =>
                {
                    b.HasOne("TavernTrashers.Api.Modules.Characters.Domain.Classes.CharacterClass", "CharacterClass")
                        .WithMany()
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_class_levels_character_classes_character_class_id");

                    b.HasOne("TavernTrashers.Api.Modules.Characters.Domain.Characters.Character", null)
                        .WithMany("ClassLevels")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_class_levels_characters_character_id");

                    b.Navigation("CharacterClass");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Resources.CharacterResource", b =>
                {
                    b.HasOne("TavernTrashers.Api.Modules.Characters.Domain.Characters.Character", null)
                        .WithMany("Resources")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_resources_characters_character_id");

                    b.HasOne("TavernTrashers.Api.Modules.Characters.Domain.Resources.ResourceDefinition", "ResourceDefinition")
                        .WithMany()
                        .HasForeignKey("ResourceDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_character_resources_resource_definitions_resource_definitio");

                    b.Navigation("ResourceDefinition");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Resources.ResourceDefinition", b =>
                {
                    b.HasOne("TavernTrashers.Api.Modules.Characters.Domain.Classes.CharacterClass", null)
                        .WithMany("ResourceDefinitions")
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resource_definitions_character_classes_character_class_id");

                    b.OwnsMany("TavernTrashers.Api.Modules.Characters.Domain.Resources.ResourceAllowance", "Allowances", b1 =>
                        {
                            b1.Property<Guid>("ResourceDefinitionId")
                                .HasColumnType("uuid")
                                .HasColumnName("resource_definition_id");

                            b1.Property<int>("Level")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("level");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Level"));

                            b1.Property<int>("Amount")
                                .HasColumnType("integer")
                                .HasColumnName("amount");

                            b1.HasKey("ResourceDefinitionId", "Level")
                                .HasName("pk_resource_allowance");

                            b1.ToTable("resource_allowance", "characters");

                            b1.WithOwner()
                                .HasForeignKey("ResourceDefinitionId")
                                .HasConstraintName("fk_resource_allowance_resource_definitions_resource_definition");
                        });

                    b.Navigation("Allowances");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Characters.Character", b =>
                {
                    b.Navigation("ClassLevels");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Classes.CharacterClass", b =>
                {
                    b.Navigation("ResourceDefinitions");
                });
#pragma warning restore 612, 618
        }
    }
}
