// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TavernTrashers.Api.Modules.Characters.Infrastructure.Database;

#nullable disable

namespace TavernTrashers.Api.Modules.Characters.Infrastructure.Database.Migrations
{
    [DbContext(typeof(CharactersDbContext))]
    partial class CharactersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("characters")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TavernTrashers.Api.Common.Infrastructure.Auditing.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("text")
                        .HasColumnName("affected_columns");

                    b.Property<string>("NewValues")
                        .HasMaxLength(3000)
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("OldValues")
                        .HasMaxLength(3000)
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("jsonb")
                        .HasColumnName("primary_key");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("table_name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.ToTable("audit_logs", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("created_by");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Campaigns.CampaignReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_campaign_read_models");

                    b.ToTable("campaign_read_models", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Characters.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<int>("Conditions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("conditions");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_characters_campaign_id");

                    b.ToTable("characters", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.ClassLevels.ClassLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_class_id");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.HasKey("Id")
                        .HasName("pk_class_levels");

                    b.HasIndex("CharacterClassId")
                        .HasDatabaseName("ix_class_levels_character_class_id");

                    b.HasIndex("CharacterId", "CharacterClassId")
                        .IsUnique()
                        .HasDatabaseName("ix_class_levels_character_id_character_class_id");

                    b.ToTable("class_levels", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Classes.CharacterClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsHomebrew")
                        .HasColumnType("boolean")
                        .HasColumnName("is_homebrew");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_character_classes");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_character_classes_name");

                    b.ToTable("character_classes", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Resources.CharacterResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<int>("CurrentAmount")
                        .HasColumnType("integer")
                        .HasColumnName("current_amount");

                    b.Property<int>("MaxAmount")
                        .HasColumnType("integer")
                        .HasColumnName("max_amount");

                    b.Property<Guid>("ResourceDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_definition_id");

                    b.HasKey("Id")
                        .HasName("pk_character_resources");

                    b.HasIndex("ResourceDefinitionId")
                        .HasDatabaseName("ix_character_resources_resource_definition_id");

                    b.HasIndex("CharacterId", "ResourceDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("ix_character_resources_character_id_resource_definition_id");

                    b.ToTable("character_resources", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Resources.DeathSavingThrows", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<int>("Failures")
                        .HasColumnType("integer")
                        .HasColumnName("failures");

                    b.Property<int>("Successes")
                        .HasColumnType("integer")
                        .HasColumnName("successes");

                    b.HasKey("Id")
                        .HasName("pk_death_saving_throws");

                    b.HasIndex("CharacterId")
                        .IsUnique()
                        .HasDatabaseName("ix_death_saving_throws_character_id");

                    b.ToTable("death_saving_throws", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Resources.GenericResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<int>("CurrentUses")
                        .HasColumnType("integer")
                        .HasColumnName("current_uses");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<int>("MaxUses")
                        .HasColumnType("integer")
                        .HasColumnName("max_uses");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("ResetTriggers")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reset_triggers");

                    b.Property<string>("SourceCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_category");

                    b.HasKey("Id")
                        .HasName("pk_generic_resources");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_generic_resources_character_id");

                    b.ToTable("generic_resources", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Resources.HitPoints", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BaseMaxHitPoints")
                        .HasColumnType("integer")
                        .HasColumnName("base_max_hit_points");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<int>("CurrentHitPoints")
                        .HasColumnType("integer")
                        .HasColumnName("current_hit_points");

                    b.Property<int>("MaxHitPointReduction")
                        .HasColumnType("integer")
                        .HasColumnName("max_hit_point_reduction");

                    b.Property<int>("TemporaryHitPoints")
                        .HasColumnType("integer")
                        .HasColumnName("temporary_hit_points");

                    b.HasKey("Id")
                        .HasName("pk_hit_points");

                    b.HasIndex("CharacterId")
                        .IsUnique()
                        .HasDatabaseName("ix_hit_points_character_id");

                    b.ToTable("hit_points", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Resources.ResourceDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_class_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_resource_definitions");

                    b.HasIndex("CharacterClassId")
                        .HasDatabaseName("ix_resource_definitions_character_class_id");

                    b.ToTable("resource_definitions", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Resources.SpellSlotLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CurrentUses")
                        .HasColumnType("integer")
                        .HasColumnName("current_uses");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("MaxUses")
                        .HasColumnType("integer")
                        .HasColumnName("max_uses");

                    b.Property<Guid>("SpellSlotPoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("spell_slot_pool_id");

                    b.HasKey("Id")
                        .HasName("pk_spell_slot_levels");

                    b.HasIndex("SpellSlotPoolId")
                        .HasDatabaseName("ix_spell_slot_levels_spell_slot_pool_id");

                    b.ToTable("spell_slot_levels", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Resources.SpellSlotPool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.HasKey("Id")
                        .HasName("pk_spell_slot_pools");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_spell_slot_pools_character_id");

                    b.ToTable("spell_slot_pools", "characters");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.ClassLevels.ClassLevel", b =>
                {
                    b.HasOne("TavernTrashers.Api.Modules.Characters.Domain.Classes.CharacterClass", "CharacterClass")
                        .WithMany()
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_class_levels_character_classes_character_class_id");

                    b.Navigation("CharacterClass");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Resources.CharacterResource", b =>
                {
                    b.HasOne("TavernTrashers.Api.Modules.Characters.Domain.Resources.ResourceDefinition", "ResourceDefinition")
                        .WithMany()
                        .HasForeignKey("ResourceDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_character_resources_resource_definitions_resource_definitio");

                    b.Navigation("ResourceDefinition");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Resources.DeathSavingThrows", b =>
                {
                    b.HasOne("TavernTrashers.Api.Modules.Characters.Domain.Characters.Character", null)
                        .WithOne("DeathSavingThrows")
                        .HasForeignKey("TavernTrashers.Api.Modules.Characters.Domain.Resources.DeathSavingThrows", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_death_saving_throws_characters_character_id");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Resources.GenericResource", b =>
                {
                    b.HasOne("TavernTrashers.Api.Modules.Characters.Domain.Characters.Character", null)
                        .WithMany("GenericResources")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_generic_resources_characters_character_id");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Resources.HitPoints", b =>
                {
                    b.HasOne("TavernTrashers.Api.Modules.Characters.Domain.Characters.Character", null)
                        .WithOne("HitPoints")
                        .HasForeignKey("TavernTrashers.Api.Modules.Characters.Domain.Resources.HitPoints", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hit_points_characters_character_id");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Resources.ResourceDefinition", b =>
                {
                    b.HasOne("TavernTrashers.Api.Modules.Characters.Domain.Classes.CharacterClass", null)
                        .WithMany("ResourceDefinitions")
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resource_definitions_character_classes_character_class_id");

                    b.OwnsMany("TavernTrashers.Api.Modules.Characters.Domain.Resources.ResourceAllowance", "Allowances", b1 =>
                        {
                            b1.Property<Guid>("ResourceDefinitionId")
                                .HasColumnType("uuid")
                                .HasColumnName("resource_definition_id");

                            b1.Property<int>("Level")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("level");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Level"));

                            b1.Property<int>("Amount")
                                .HasColumnType("integer")
                                .HasColumnName("amount");

                            b1.HasKey("ResourceDefinitionId", "Level")
                                .HasName("pk_resource_allowance");

                            b1.ToTable("resource_allowance", "characters");

                            b1.WithOwner()
                                .HasForeignKey("ResourceDefinitionId")
                                .HasConstraintName("fk_resource_allowance_resource_definitions_resource_definition");
                        });

                    b.Navigation("Allowances");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Resources.SpellSlotLevel", b =>
                {
                    b.HasOne("TavernTrashers.Api.Modules.Characters.Domain.Resources.SpellSlotPool", null)
                        .WithMany("Levels")
                        .HasForeignKey("SpellSlotPoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spell_slot_levels_spell_slot_pools_spell_slot_pool_id");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Resources.SpellSlotPool", b =>
                {
                    b.HasOne("TavernTrashers.Api.Modules.Characters.Domain.Characters.Character", null)
                        .WithMany("SpellSlotPools")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spell_slot_pools_characters_character_id");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Characters.Character", b =>
                {
                    b.Navigation("DeathSavingThrows")
                        .IsRequired();

                    b.Navigation("GenericResources");

                    b.Navigation("HitPoints")
                        .IsRequired();

                    b.Navigation("SpellSlotPools");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Classes.CharacterClass", b =>
                {
                    b.Navigation("ResourceDefinitions");
                });

            modelBuilder.Entity("TavernTrashers.Api.Modules.Characters.Domain.Resources.SpellSlotPool", b =>
                {
                    b.Navigation("Levels");
                });
#pragma warning restore 612, 618
        }
    }
}
